name: Example

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run CTRF summary
      run: npx github-actions-ctrf ctrf-report.json
