name: main

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 2 * * *'

jobs:
  testing:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' || github.event_name != 'schedule'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npx tsc
    - name: Test test PR comment
      run: node dist/index.js ctrf-report.json --pr-comment
      if: github.event_name != 'schedule'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test PR with custom message string
      run: node dist/index.js ctrf-report.json --pr-comment --pr-comment-message "## This is a heading" --title "PR With String"
      if: github.event_name != 'schedule'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test PR with custom message hbs file
      run: node dist/index.js ctrf-report.json --pr-comment --pr-comment-message "src/templates/custom-pr.hbs" --title "PR With HandleBars file"
      if: github.event_name != 'schedule'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test all
      run: node dist/index.js ctrf-report.json --title All
      if: github.event_name != 'schedule'
    - name: Test summary
      run: node dist/index.js summary ctrf-report.json --title Summary
      if: github.event_name != 'schedule'
    - name: Test flaky
      run: node dist/index.js flaky ctrf-report.json --title Flaky
      if: github.event_name != 'schedule'
    - name: Test failed
      run: node dist/index.js summary ctrf-report.json --title Failed
      if: github.event_name != 'schedule'
    - name: Test detailed
      run: node dist/index.js detailed ctrf-report.json --title Detailed
      if: github.event_name != 'schedule'
    - name: Test no title
      run: node dist/index.js summary ctrf-report.json
      if: github.event_name != 'schedule'
    - name: Test schedule context
      run: node dist/index.js ctrf-report.json
      if: github.event_name == 'schedule'