name: main

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 2 * * *'

jobs:
  testing:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' || github.event_name != 'schedule'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npx tsc
    - name: Test push or PR context
      run: node dist/index.js --file=ctrf-report.json --post-comment
      if: github.event_name != 'schedule'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test schedule context
      run: node dist/index.js --file=ctrf-report.json
      if: github.event_name == 'schedule'
