name: main

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 2 * * *'

jobs:
  testing:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' || github.event_name != 'schedule'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npx tsc
    - name: Test all
      run: node dist/index.js ctrf-reports/ctrf-report.json --title All
      if: github.event_name != 'schedule'
    - name: Test summary
      run: node dist/index.js summary ctrf-reports/ctrf-report.json --title Summary
      if: github.event_name != 'schedule'
    - name: Test flaky
      run: node dist/index.js flaky ctrf-reports/ctrf-report.json --title Flaky
      if: github.event_name != 'schedule'
    - name: Test failed
      run: node dist/index.js failed ctrf-reports/ctrf-report.json --title Failed
      if: github.event_name != 'schedule'
    - name: Test failed no title
      run: node dist/index.js failed ctrf-reports/ctrf-report.json
      if: github.event_name != 'schedule'
    - name: Test detailed
      run: node dist/index.js tests ctrf-reports/ctrf-report.json --title Detailed
      if: github.event_name != 'schedule'
    - name: Test historical
      run: node dist/index.js historical ctrf-reports/ctrf-report.json --annotate false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name != 'schedule'
    - name: Test default title
      run: node dist/index.js ctrf-reports/ctrf-report.json --annotate false
      if: github.event_name != 'schedule'
    - name: Test no title
      run: node dist/index.js ctrf-reports/ctrf-report.json --annotate false
      if: github.event_name != 'schedule'
    - name: Test no fails or flaky
      run: node dist/index.js ctrf-reports/ctrf-report-no-fails.json
      if: github.event_name != 'schedule'
    - name: Test custom summary hbs file
      run: node dist/index.js custom ctrf-reports/ctrf-report.json templates/custom-summary.hbs
      if: github.event_name != 'schedule'
    - name: Test custom summary string
      run: node dist/index.js custom ctrf-reports/ctrf-report.json "I'm a custom summary string!"
      if: github.event_name != 'schedule'
    - name: Test test PR comment
      run: node dist/index.js ctrf-reports/ctrf-report.json --pr-comment --title "With PR Comment" --annotate false
      if: github.event_name != 'schedule'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test test PR comment no fails
      run: node dist/index.js ctrf-reports/ctrf-report-no-fails.json --pr-comment --title "With PR Comment No Fails" --annotate false
      if: github.event_name != 'schedule'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test PR with custom message string
      run: node dist/index.js ctrf-reports/ctrf-report.json --pr-comment --pr-comment-message "## This is a custom message with string!" --title "PR With String" --annotate false
      if: github.event_name != 'schedule'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test PR with custom message hbs file
      run: node dist/index.js ctrf-reports/ctrf-report.json --pr-comment --pr-comment-message "templates/custom-summary.hbs" --title "PR With HandleBars file" --annotate false
      if: github.event_name != 'schedule'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test schedule context
      run: node dist/index.js ctrf-reports/ctrf-report.json
      if: github.event_name == 'schedule'